language: node_js
node_js:
  - "stable"
  - "10"
  - "8"
  - "6"
  - "5"
  - "4"
script:
  - npm run lint
  - npm test
after_script:
  - npm run coveralls
deploy:
  provider: npm
  email: "luke@c2cschools.com"
  api_key: "$NPM_API_KEY"
  on:
    branch: master
